filter:
    excluded_paths:
        - 'tests/*'
        - 'features/*'

checks:
    php: true

build:
    dependencies:
        before:
            - sudo apt-get -y install libmagickwand-dev libmagickcore-dev
            - printf "\n" | pecl install imagick
            - sed -i 's/extension="imagick.so"//g' `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    environment:
        php:
            version: 7.2
    tests:
        override:
            -
                command: bin/phpunit --coverage-clover=clover.xml
                coverage:
                    file: clover.xml
                    format: php-clover
#            -
#                command: vendor/bin/behat
