filter:
    excluded_paths:
        - 'tests/*'
        - 'features/*'

checks:
    php: true

build:
    dependencies:
        before:
            - sudo apt-get -y install libmagickwand-dev libmagickcore-dev
            - printf "\n" | pecl install imagick
    environment:
        php:
            version: 7.2
            ini:
                'date.timezone': 'Europe/London'
                memory_limit: -1
    tests:
        override:
            -
                command: bin/phpunit --coverage-clover=clover.xml
                coverage:
                    file: clover.xml
                    format: php-clover
#            -
#                command: vendor/bin/behat
