filter:
    excluded_paths:
        - 'tests/*'
        - 'features/*'

checks:
    php: true

build:
    dependencies:
        before:
            - sudo apt-get -y install libmagickwand-dev libmagickcore-dev
            - printf "\n" | pecl install imagick
    environment:
        variables:
            SYMFONY_DEPRECATIONS_HELPER: disabled
        php:
            version: 7.2
            ini:
                'date.timezone': 'Europe/London'
                memory_limit: -1
    tests:
        override:
            -
                command: tests/Functional/app/console cache:clear
            -
                command: vendor/bin/simple-phpunit --coverage-clover=coverage.xml
                coverage:
                    file: clover.xml
                    format: php-clover
            -
                command: vendor/bin/behat --format=progress
