language: php

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled

jobs:
    include:
        - php: '7.2'
        - php: '7.2'
          env: deps=low
        - php: '7.2'
          env: SYMFONY_DEPRECATIONS_HELPER=0
    allow_failures:
        - php: '7.2'
          env: SYMFONY_DEPRECATIONS_HELPER=0

matrix:
    fast_finish: true

before_install:
    - printf "\n" | pecl install imagick
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - phpenv config-add travis.php.ini
    - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
    - if [[ $deps = 'low' ]]; then
        composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi;
      else
        composer update --prefer-dist --no-progress --no-suggest --ansi;
      fi

before_script:
    - composer install --prefer-source

script:
    - tests/app/console cache:clear
    - bin/phpunit --coverage-clover=coverage.xml
#    - vendor/bin/behat

notifications:
    email:
        - daniel@silverback.is

after_success:
    - bash <(curl -s https://codecov.io/bash)
