language: php

php:
    - 7.1.3
    - 7.2

env:
    global:
        SYMFONY_DEPRECATIONS_HELPER: disabled
    matrix:
        - SYMFONY_VERSION="^3.4"
        - SYMFONY_VERSION="^4"
        - SYMFONY_VERSION="dev-master"

before_install:
    - printf "\n" | pecl install imagick
    - phpenv config-add travis.php.ini

install:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION}

before_script:
    - composer install --prefer-source

script:
    - bin/phpunit --coverage-clover=coverage.xml
#    - vendor/bin/behat

notifications:
    email:
        - daniel@silverback.is

after_success:
    - bash <(curl -s https://codecov.io/bash)
