sudo: required

services:
    - docker

before_script:
    - docker-compose up -d

script:
    - docker-compose exec php vendor/bin/simple-phpunit

notifications:
    email:
        - daniel@silverback.is

after_success:
    - bash <(curl -s https://codecov.io/bash)
