language: php

php:
    - 7.1.3
    - 7.2

env:
    - SYMFONY_VERSION="^3.4"
    - SYMFONY_VERSION="^4"
    - SYMFONY_VERSION=dev-master

before_install:
    - printf "\n" | pecl install imagick

install:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION}

before_script:
    - composer install --prefer-source --dev

script:
    - bin/phpunit --coverage-clover=coverage.xml
#    - vendor/bin/behat

notifications:
    email:
        - daniel@silverback.is

after_success:
    - bash <(curl -s https://codecov.io/bash)
