version: '3'

services:
    php:
        build:
            context: ./
            dockerfile: ./_docker/php/Dockerfile
        env_file:
            - ./.env
        volumes:
            - ./:/srv/api:rw
        restart: on-failure
        ports:
            - "8001:8000"
