version: '3'

services:
    php:
        build:
            context: ./
            dockerfile: ./_docker/php/Dockerfile
        env_file:
            - ./.env
        volumes:
            - ./:/srv:rw
        restart: on-failure
