version: '3'

services:
#    rabbitmq:
#        image: 'rabbitmq:alpine'
#        hostname: 'rabbitmq'
#        env_file:
#            - ./.env
#        ports:
#            - "15673:15672"
#            - "5673:5672"
#        volumes:
#            - "./_docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"

    php:
        build:
            context: ./
            dockerfile: ./_docker/php/Dockerfile
        env_file:
            - ./.env
        volumes:
            - ./:/srv:rw
        depends_on:
          - rabbitmq
        restart: on-failure

volumes:
    db-mysql:
