version: '3'

services:
    php:
        build:
            context: ./
            dockerfile: ./_docker/php/Dockerfile
        env_file:
            - ./.env
        volumes:
            - ./:/srv:rw

    rabbitmq:
        image: 'rabbitmq:alpine'
        hostname: 'rabbitmq'
        env_file:
            - ./.env
        ports:
            - "15672:15672"
            - "5672:5672"
        volumes:
            - "./_docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
            #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"

volumes:
    db-mysql:
